### PR TITLE
 Updated to work with Electra Jailbreak Toolkit for iOS 11.0-11.1.2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Siguza** [comment]
Why is that not something the jailbreak handles?

**Comment by ghost** [comment]
I'm not sure that I can answer this question.

**Comment by ghost** [comment]
Should I close this pull request?

**Comment by Siguza** [comment]
From what I hear, Electra should be getting an update in the not too distant future to deal with this.  
So yes, unless new problems arise, I consider this resolved.

**Pull request closed without merging**
